#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Pyxis")]
	public partial class PyxisdblDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertUsuarios(Usuarios instance);
    partial void UpdateUsuarios(Usuarios instance);
    partial void DeleteUsuarios(Usuarios instance);
    partial void Insertcalificaciones(calificaciones instance);
    partial void Updatecalificaciones(calificaciones instance);
    partial void Deletecalificaciones(calificaciones instance);
    partial void Insertmascotas(mascotas instance);
    partial void Updatemascotas(mascotas instance);
    partial void Deletemascotas(mascotas instance);
    partial void Insertpaseadores(paseadores instance);
    partial void Updatepaseadores(paseadores instance);
    partial void Deletepaseadores(paseadores instance);
    partial void InsertPQR(PQR instance);
    partial void UpdatePQR(PQR instance);
    partial void DeletePQR(PQR instance);
    partial void Insertservicio(servicio instance);
    partial void Updateservicio(servicio instance);
    partial void Deleteservicio(servicio instance);
    #endregion
		
		public PyxisdblDataContext() : 
				base(global::DataBase.Properties.Settings.Default.PyxisConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public PyxisdblDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PyxisdblDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PyxisdblDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PyxisdblDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Usuarios> Usuarios
		{
			get
			{
				return this.GetTable<Usuarios>();
			}
		}
		
		public System.Data.Linq.Table<calificaciones> calificaciones
		{
			get
			{
				return this.GetTable<calificaciones>();
			}
		}
		
		public System.Data.Linq.Table<mascotas> mascotas
		{
			get
			{
				return this.GetTable<mascotas>();
			}
		}
		
		public System.Data.Linq.Table<paseadores> paseadores
		{
			get
			{
				return this.GetTable<paseadores>();
			}
		}
		
		public System.Data.Linq.Table<PQR> PQR
		{
			get
			{
				return this.GetTable<PQR>();
			}
		}
		
		public System.Data.Linq.Table<servicio> servicio
		{
			get
			{
				return this.GetTable<servicio>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ActualizarUsuario")]
		public int ActualizarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="VarChar(50)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDO", DbType="VarChar(50)")] string aPELLIDO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TELEFONO", DbType="BigInt")] System.Nullable<long> tELEFONO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BARRIO", DbType="VarChar(50)")] string bARRIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO", DbType="VarChar(100)")] string cORREO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, nOMBRE, aPELLIDO, tELEFONO, bARRIO, cORREO);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.OrganizarPaseador")]
		public ISingleResult<OrganizarPaseadorResult> OrganizarPaseador()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<OrganizarPaseadorResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Crearpaseador")]
		public int Crearpaseador([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string disponibilidad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Experiencia", DbType="VarChar(20)")] string experiencia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Especialidad", DbType="VarChar(50)")] string especialidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> precio)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, disponibilidad, experiencia, especialidad, precio);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CrearUsuario")]
		public int CrearUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="VarChar(50)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDO", DbType="VarChar(50)")] string aPELLIDO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONTRASENA", DbType="VarChar(50)")] string cONTRASENA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO", DbType="VarChar(100)")] string cORREO, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string barrio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> documento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string tipodoc)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMBRE, aPELLIDO, cONTRASENA, cORREO, telefono, barrio, documento, tipodoc);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Consultarpaseador")]
		public ISingleResult<ConsultarpaseadorResult> Consultarpaseador([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<ConsultarpaseadorResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.buscarpaseadorN")]
		public ISingleResult<buscarpaseadorNResult> buscarpaseadorN([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre);
			return ((ISingleResult<buscarpaseadorNResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Inactivarpaseador")]
		public int Inactivarpaseador([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuarios")]
	public partial class Usuarios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Idusuario;
		
		private string _nombre;
		
		private string _apellido;
		
		private string _correo;
		
		private int _documento;
		
		private string _tipo_doc;
		
		private string _barrio;
		
		private System.Nullable<long> _telefono;
		
		private string _contrasena;
		
		private EntitySet<mascotas> _mascotas;
		
		private EntitySet<paseadores> _paseadores;
		
		private EntitySet<PQR> _PQR;
		
		private EntitySet<servicio> _servicio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdusuarioChanging(int value);
    partial void OnIdusuarioChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidoChanging(string value);
    partial void OnapellidoChanged();
    partial void OncorreoChanging(string value);
    partial void OncorreoChanged();
    partial void OndocumentoChanging(int value);
    partial void OndocumentoChanged();
    partial void Ontipo_docChanging(string value);
    partial void Ontipo_docChanged();
    partial void OnbarrioChanging(string value);
    partial void OnbarrioChanged();
    partial void OntelefonoChanging(System.Nullable<long> value);
    partial void OntelefonoChanged();
    partial void OncontrasenaChanging(string value);
    partial void OncontrasenaChanged();
    #endregion
		
		public Usuarios()
		{
			this._mascotas = new EntitySet<mascotas>(new Action<mascotas>(this.attach_mascotas), new Action<mascotas>(this.detach_mascotas));
			this._paseadores = new EntitySet<paseadores>(new Action<paseadores>(this.attach_paseadores), new Action<paseadores>(this.detach_paseadores));
			this._PQR = new EntitySet<PQR>(new Action<PQR>(this.attach_PQR), new Action<PQR>(this.detach_PQR));
			this._servicio = new EntitySet<servicio>(new Action<servicio>(this.attach_servicio), new Action<servicio>(this.detach_servicio));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idusuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Idusuario
		{
			get
			{
				return this._Idusuario;
			}
			set
			{
				if ((this._Idusuario != value))
				{
					this.OnIdusuarioChanging(value);
					this.SendPropertyChanging();
					this._Idusuario = value;
					this.SendPropertyChanged("Idusuario");
					this.OnIdusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this.OnapellidoChanging(value);
					this.SendPropertyChanging();
					this._apellido = value;
					this.SendPropertyChanged("apellido");
					this.OnapellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this.OncorreoChanging(value);
					this.SendPropertyChanging();
					this._correo = value;
					this.SendPropertyChanged("correo");
					this.OncorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_documento", DbType="Int NOT NULL")]
		public int documento
		{
			get
			{
				return this._documento;
			}
			set
			{
				if ((this._documento != value))
				{
					this.OndocumentoChanging(value);
					this.SendPropertyChanging();
					this._documento = value;
					this.SendPropertyChanged("documento");
					this.OndocumentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_doc", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string tipo_doc
		{
			get
			{
				return this._tipo_doc;
			}
			set
			{
				if ((this._tipo_doc != value))
				{
					this.Ontipo_docChanging(value);
					this.SendPropertyChanging();
					this._tipo_doc = value;
					this.SendPropertyChanged("tipo_doc");
					this.Ontipo_docChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_barrio", DbType="VarChar(50)")]
		public string barrio
		{
			get
			{
				return this._barrio;
			}
			set
			{
				if ((this._barrio != value))
				{
					this.OnbarrioChanging(value);
					this.SendPropertyChanging();
					this._barrio = value;
					this.SendPropertyChanged("barrio");
					this.OnbarrioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="BigInt")]
		public System.Nullable<long> telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contrasena", DbType="VarChar(50)")]
		public string contrasena
		{
			get
			{
				return this._contrasena;
			}
			set
			{
				if ((this._contrasena != value))
				{
					this.OncontrasenaChanging(value);
					this.SendPropertyChanging();
					this._contrasena = value;
					this.SendPropertyChanged("contrasena");
					this.OncontrasenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_mascotas", Storage="_mascotas", ThisKey="Idusuario", OtherKey="Idusuario")]
		public EntitySet<mascotas> mascotas
		{
			get
			{
				return this._mascotas;
			}
			set
			{
				this._mascotas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_paseadores", Storage="_paseadores", ThisKey="Idusuario", OtherKey="pa_idusu")]
		public EntitySet<paseadores> paseadores
		{
			get
			{
				return this._paseadores;
			}
			set
			{
				this._paseadores.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_PQR", Storage="_PQR", ThisKey="Idusuario", OtherKey="idusu")]
		public EntitySet<PQR> PQR
		{
			get
			{
				return this._PQR;
			}
			set
			{
				this._PQR.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_servicio", Storage="_servicio", ThisKey="Idusuario", OtherKey="se_idusuario")]
		public EntitySet<servicio> servicio
		{
			get
			{
				return this._servicio;
			}
			set
			{
				this._servicio.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_mascotas(mascotas entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = this;
		}
		
		private void detach_mascotas(mascotas entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = null;
		}
		
		private void attach_paseadores(paseadores entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = this;
		}
		
		private void detach_paseadores(paseadores entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = null;
		}
		
		private void attach_PQR(PQR entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = this;
		}
		
		private void detach_PQR(PQR entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = null;
		}
		
		private void attach_servicio(servicio entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = this;
		}
		
		private void detach_servicio(servicio entity)
		{
			this.SendPropertyChanging();
			entity.Usuarios = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.calificaciones")]
	public partial class calificaciones : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Idcalificacion;
		
		private string _opinion;
		
		private int _puntuacion;
		
		private System.Nullable<System.DateTime> _fecha_ca;
		
		private System.Nullable<int> _servicioId;
		
		private EntityRef<servicio> _servicio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdcalificacionChanging(int value);
    partial void OnIdcalificacionChanged();
    partial void OnopinionChanging(string value);
    partial void OnopinionChanged();
    partial void OnpuntuacionChanging(int value);
    partial void OnpuntuacionChanged();
    partial void Onfecha_caChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_caChanged();
    partial void OnservicioIdChanging(System.Nullable<int> value);
    partial void OnservicioIdChanged();
    #endregion
		
		public calificaciones()
		{
			this._servicio = default(EntityRef<servicio>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idcalificacion", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Idcalificacion
		{
			get
			{
				return this._Idcalificacion;
			}
			set
			{
				if ((this._Idcalificacion != value))
				{
					this.OnIdcalificacionChanging(value);
					this.SendPropertyChanging();
					this._Idcalificacion = value;
					this.SendPropertyChanged("Idcalificacion");
					this.OnIdcalificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_opinion", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string opinion
		{
			get
			{
				return this._opinion;
			}
			set
			{
				if ((this._opinion != value))
				{
					this.OnopinionChanging(value);
					this.SendPropertyChanging();
					this._opinion = value;
					this.SendPropertyChanged("opinion");
					this.OnopinionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_puntuacion", DbType="Int NOT NULL")]
		public int puntuacion
		{
			get
			{
				return this._puntuacion;
			}
			set
			{
				if ((this._puntuacion != value))
				{
					this.OnpuntuacionChanging(value);
					this.SendPropertyChanging();
					this._puntuacion = value;
					this.SendPropertyChanged("puntuacion");
					this.OnpuntuacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_ca", DbType="Date")]
		public System.Nullable<System.DateTime> fecha_ca
		{
			get
			{
				return this._fecha_ca;
			}
			set
			{
				if ((this._fecha_ca != value))
				{
					this.Onfecha_caChanging(value);
					this.SendPropertyChanging();
					this._fecha_ca = value;
					this.SendPropertyChanged("fecha_ca");
					this.Onfecha_caChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_servicioId", DbType="Int")]
		public System.Nullable<int> servicioId
		{
			get
			{
				return this._servicioId;
			}
			set
			{
				if ((this._servicioId != value))
				{
					if (this._servicio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnservicioIdChanging(value);
					this.SendPropertyChanging();
					this._servicioId = value;
					this.SendPropertyChanged("servicioId");
					this.OnservicioIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="servicio_calificaciones", Storage="_servicio", ThisKey="servicioId", OtherKey="Idservicio", IsForeignKey=true)]
		public servicio servicio
		{
			get
			{
				return this._servicio.Entity;
			}
			set
			{
				servicio previousValue = this._servicio.Entity;
				if (((previousValue != value) 
							|| (this._servicio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._servicio.Entity = null;
						previousValue.calificaciones.Remove(this);
					}
					this._servicio.Entity = value;
					if ((value != null))
					{
						value.calificaciones.Add(this);
						this._servicioId = value.Idservicio;
					}
					else
					{
						this._servicioId = default(Nullable<int>);
					}
					this.SendPropertyChanged("servicio");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mascotas")]
	public partial class mascotas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Idmascota;
		
		private string _tamaño;
		
		private string _edad;
		
		private string _raza;
		
		private string _nombre_ma;
		
		private System.Nullable<int> _Idusuario;
		
		private EntityRef<Usuarios> _Usuarios;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdmascotaChanging(int value);
    partial void OnIdmascotaChanged();
    partial void OntamañoChanging(string value);
    partial void OntamañoChanged();
    partial void OnedadChanging(string value);
    partial void OnedadChanged();
    partial void OnrazaChanging(string value);
    partial void OnrazaChanged();
    partial void Onnombre_maChanging(string value);
    partial void Onnombre_maChanged();
    partial void OnIdusuarioChanging(System.Nullable<int> value);
    partial void OnIdusuarioChanged();
    #endregion
		
		public mascotas()
		{
			this._Usuarios = default(EntityRef<Usuarios>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idmascota", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Idmascota
		{
			get
			{
				return this._Idmascota;
			}
			set
			{
				if ((this._Idmascota != value))
				{
					this.OnIdmascotaChanging(value);
					this.SendPropertyChanging();
					this._Idmascota = value;
					this.SendPropertyChanged("Idmascota");
					this.OnIdmascotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tamaño", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string tamaño
		{
			get
			{
				return this._tamaño;
			}
			set
			{
				if ((this._tamaño != value))
				{
					this.OntamañoChanging(value);
					this.SendPropertyChanging();
					this._tamaño = value;
					this.SendPropertyChanged("tamaño");
					this.OntamañoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_edad", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string edad
		{
			get
			{
				return this._edad;
			}
			set
			{
				if ((this._edad != value))
				{
					this.OnedadChanging(value);
					this.SendPropertyChanging();
					this._edad = value;
					this.SendPropertyChanged("edad");
					this.OnedadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_raza", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string raza
		{
			get
			{
				return this._raza;
			}
			set
			{
				if ((this._raza != value))
				{
					this.OnrazaChanging(value);
					this.SendPropertyChanging();
					this._raza = value;
					this.SendPropertyChanged("raza");
					this.OnrazaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_ma", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre_ma
		{
			get
			{
				return this._nombre_ma;
			}
			set
			{
				if ((this._nombre_ma != value))
				{
					this.Onnombre_maChanging(value);
					this.SendPropertyChanging();
					this._nombre_ma = value;
					this.SendPropertyChanged("nombre_ma");
					this.Onnombre_maChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idusuario", DbType="Int")]
		public System.Nullable<int> Idusuario
		{
			get
			{
				return this._Idusuario;
			}
			set
			{
				if ((this._Idusuario != value))
				{
					if (this._Usuarios.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdusuarioChanging(value);
					this.SendPropertyChanging();
					this._Idusuario = value;
					this.SendPropertyChanged("Idusuario");
					this.OnIdusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_mascotas", Storage="_Usuarios", ThisKey="Idusuario", OtherKey="Idusuario", IsForeignKey=true)]
		public Usuarios Usuarios
		{
			get
			{
				return this._Usuarios.Entity;
			}
			set
			{
				Usuarios previousValue = this._Usuarios.Entity;
				if (((previousValue != value) 
							|| (this._Usuarios.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuarios.Entity = null;
						previousValue.mascotas.Remove(this);
					}
					this._Usuarios.Entity = value;
					if ((value != null))
					{
						value.mascotas.Add(this);
						this._Idusuario = value.Idusuario;
					}
					else
					{
						this._Idusuario = default(Nullable<int>);
					}
					this.SendPropertyChanged("Usuarios");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.paseadores")]
	public partial class paseadores : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Idpaseador;
		
		private string _disponibilidad;
		
		private string _experiencia;
		
		private System.Nullable<double> _calificacion_prom;
		
		private string _especialidad;
		
		private System.Nullable<int> _pa_idusu;
		
		private System.Nullable<double> _precio;
		
		private string _estado;
		
		private EntitySet<PQR> _PQR;
		
		private EntityRef<Usuarios> _Usuarios;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdpaseadorChanging(int value);
    partial void OnIdpaseadorChanged();
    partial void OndisponibilidadChanging(string value);
    partial void OndisponibilidadChanged();
    partial void OnexperienciaChanging(string value);
    partial void OnexperienciaChanged();
    partial void Oncalificacion_promChanging(System.Nullable<double> value);
    partial void Oncalificacion_promChanged();
    partial void OnespecialidadChanging(string value);
    partial void OnespecialidadChanged();
    partial void Onpa_idusuChanging(System.Nullable<int> value);
    partial void Onpa_idusuChanged();
    partial void OnprecioChanging(System.Nullable<double> value);
    partial void OnprecioChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    #endregion
		
		public paseadores()
		{
			this._PQR = new EntitySet<PQR>(new Action<PQR>(this.attach_PQR), new Action<PQR>(this.detach_PQR));
			this._Usuarios = default(EntityRef<Usuarios>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idpaseador", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Idpaseador
		{
			get
			{
				return this._Idpaseador;
			}
			set
			{
				if ((this._Idpaseador != value))
				{
					this.OnIdpaseadorChanging(value);
					this.SendPropertyChanging();
					this._Idpaseador = value;
					this.SendPropertyChanged("Idpaseador");
					this.OnIdpaseadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_disponibilidad", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string disponibilidad
		{
			get
			{
				return this._disponibilidad;
			}
			set
			{
				if ((this._disponibilidad != value))
				{
					this.OndisponibilidadChanging(value);
					this.SendPropertyChanging();
					this._disponibilidad = value;
					this.SendPropertyChanged("disponibilidad");
					this.OndisponibilidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_experiencia", DbType="VarChar(20)")]
		public string experiencia
		{
			get
			{
				return this._experiencia;
			}
			set
			{
				if ((this._experiencia != value))
				{
					this.OnexperienciaChanging(value);
					this.SendPropertyChanging();
					this._experiencia = value;
					this.SendPropertyChanged("experiencia");
					this.OnexperienciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_calificacion_prom", DbType="Float")]
		public System.Nullable<double> calificacion_prom
		{
			get
			{
				return this._calificacion_prom;
			}
			set
			{
				if ((this._calificacion_prom != value))
				{
					this.Oncalificacion_promChanging(value);
					this.SendPropertyChanging();
					this._calificacion_prom = value;
					this.SendPropertyChanged("calificacion_prom");
					this.Oncalificacion_promChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_especialidad", DbType="VarChar(50)")]
		public string especialidad
		{
			get
			{
				return this._especialidad;
			}
			set
			{
				if ((this._especialidad != value))
				{
					this.OnespecialidadChanging(value);
					this.SendPropertyChanging();
					this._especialidad = value;
					this.SendPropertyChanged("especialidad");
					this.OnespecialidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pa_idusu", DbType="Int")]
		public System.Nullable<int> pa_idusu
		{
			get
			{
				return this._pa_idusu;
			}
			set
			{
				if ((this._pa_idusu != value))
				{
					if (this._Usuarios.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpa_idusuChanging(value);
					this.SendPropertyChanging();
					this._pa_idusu = value;
					this.SendPropertyChanged("pa_idusu");
					this.Onpa_idusuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Float")]
		public System.Nullable<double> precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this.OnprecioChanging(value);
					this.SendPropertyChanging();
					this._precio = value;
					this.SendPropertyChanged("precio");
					this.OnprecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="VarChar(10)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="paseadores_PQR", Storage="_PQR", ThisKey="Idpaseador", OtherKey="idpas")]
		public EntitySet<PQR> PQR
		{
			get
			{
				return this._PQR;
			}
			set
			{
				this._PQR.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_paseadores", Storage="_Usuarios", ThisKey="pa_idusu", OtherKey="Idusuario", IsForeignKey=true)]
		public Usuarios Usuarios
		{
			get
			{
				return this._Usuarios.Entity;
			}
			set
			{
				Usuarios previousValue = this._Usuarios.Entity;
				if (((previousValue != value) 
							|| (this._Usuarios.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuarios.Entity = null;
						previousValue.paseadores.Remove(this);
					}
					this._Usuarios.Entity = value;
					if ((value != null))
					{
						value.paseadores.Add(this);
						this._pa_idusu = value.Idusuario;
					}
					else
					{
						this._pa_idusu = default(Nullable<int>);
					}
					this.SendPropertyChanged("Usuarios");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PQR(PQR entity)
		{
			this.SendPropertyChanging();
			entity.paseadores = this;
		}
		
		private void detach_PQR(PQR entity)
		{
			this.SendPropertyChanging();
			entity.paseadores = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PQR")]
	public partial class PQR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdPQR;
		
		private System.DateTime _fecha_PQR;
		
		private string _comentario;
		
		private System.Nullable<int> _idusu;
		
		private System.Nullable<int> _idpas;
		
		private EntityRef<Usuarios> _Usuarios;
		
		private EntityRef<paseadores> _paseadores;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPQRChanging(int value);
    partial void OnIdPQRChanged();
    partial void Onfecha_PQRChanging(System.DateTime value);
    partial void Onfecha_PQRChanged();
    partial void OncomentarioChanging(string value);
    partial void OncomentarioChanged();
    partial void OnidusuChanging(System.Nullable<int> value);
    partial void OnidusuChanged();
    partial void OnidpasChanging(System.Nullable<int> value);
    partial void OnidpasChanged();
    #endregion
		
		public PQR()
		{
			this._Usuarios = default(EntityRef<Usuarios>);
			this._paseadores = default(EntityRef<paseadores>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPQR", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdPQR
		{
			get
			{
				return this._IdPQR;
			}
			set
			{
				if ((this._IdPQR != value))
				{
					this.OnIdPQRChanging(value);
					this.SendPropertyChanging();
					this._IdPQR = value;
					this.SendPropertyChanged("IdPQR");
					this.OnIdPQRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_PQR", DbType="Date NOT NULL")]
		public System.DateTime fecha_PQR
		{
			get
			{
				return this._fecha_PQR;
			}
			set
			{
				if ((this._fecha_PQR != value))
				{
					this.Onfecha_PQRChanging(value);
					this.SendPropertyChanging();
					this._fecha_PQR = value;
					this.SendPropertyChanged("fecha_PQR");
					this.Onfecha_PQRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comentario", DbType="VarChar(100)")]
		public string comentario
		{
			get
			{
				return this._comentario;
			}
			set
			{
				if ((this._comentario != value))
				{
					this.OncomentarioChanging(value);
					this.SendPropertyChanging();
					this._comentario = value;
					this.SendPropertyChanged("comentario");
					this.OncomentarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idusu", DbType="Int")]
		public System.Nullable<int> idusu
		{
			get
			{
				return this._idusu;
			}
			set
			{
				if ((this._idusu != value))
				{
					if (this._Usuarios.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidusuChanging(value);
					this.SendPropertyChanging();
					this._idusu = value;
					this.SendPropertyChanged("idusu");
					this.OnidusuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idpas", DbType="Int")]
		public System.Nullable<int> idpas
		{
			get
			{
				return this._idpas;
			}
			set
			{
				if ((this._idpas != value))
				{
					if (this._paseadores.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidpasChanging(value);
					this.SendPropertyChanging();
					this._idpas = value;
					this.SendPropertyChanged("idpas");
					this.OnidpasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_PQR", Storage="_Usuarios", ThisKey="idusu", OtherKey="Idusuario", IsForeignKey=true)]
		public Usuarios Usuarios
		{
			get
			{
				return this._Usuarios.Entity;
			}
			set
			{
				Usuarios previousValue = this._Usuarios.Entity;
				if (((previousValue != value) 
							|| (this._Usuarios.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuarios.Entity = null;
						previousValue.PQR.Remove(this);
					}
					this._Usuarios.Entity = value;
					if ((value != null))
					{
						value.PQR.Add(this);
						this._idusu = value.Idusuario;
					}
					else
					{
						this._idusu = default(Nullable<int>);
					}
					this.SendPropertyChanged("Usuarios");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="paseadores_PQR", Storage="_paseadores", ThisKey="idpas", OtherKey="Idpaseador", IsForeignKey=true)]
		public paseadores paseadores
		{
			get
			{
				return this._paseadores.Entity;
			}
			set
			{
				paseadores previousValue = this._paseadores.Entity;
				if (((previousValue != value) 
							|| (this._paseadores.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._paseadores.Entity = null;
						previousValue.PQR.Remove(this);
					}
					this._paseadores.Entity = value;
					if ((value != null))
					{
						value.PQR.Add(this);
						this._idpas = value.Idpaseador;
					}
					else
					{
						this._idpas = default(Nullable<int>);
					}
					this.SendPropertyChanged("paseadores");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.servicio")]
	public partial class servicio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Idservicio;
		
		private System.DateTime _fecha_se;
		
		private string _estado_se;
		
		private string _detalles_se;
		
		private System.Nullable<int> _se_idusuario;
		
		private EntitySet<calificaciones> _calificaciones;
		
		private EntityRef<Usuarios> _Usuarios;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdservicioChanging(int value);
    partial void OnIdservicioChanged();
    partial void Onfecha_seChanging(System.DateTime value);
    partial void Onfecha_seChanged();
    partial void Onestado_seChanging(string value);
    partial void Onestado_seChanged();
    partial void Ondetalles_seChanging(string value);
    partial void Ondetalles_seChanged();
    partial void Onse_idusuarioChanging(System.Nullable<int> value);
    partial void Onse_idusuarioChanged();
    #endregion
		
		public servicio()
		{
			this._calificaciones = new EntitySet<calificaciones>(new Action<calificaciones>(this.attach_calificaciones), new Action<calificaciones>(this.detach_calificaciones));
			this._Usuarios = default(EntityRef<Usuarios>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idservicio", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Idservicio
		{
			get
			{
				return this._Idservicio;
			}
			set
			{
				if ((this._Idservicio != value))
				{
					this.OnIdservicioChanging(value);
					this.SendPropertyChanging();
					this._Idservicio = value;
					this.SendPropertyChanged("Idservicio");
					this.OnIdservicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_se", DbType="Date NOT NULL")]
		public System.DateTime fecha_se
		{
			get
			{
				return this._fecha_se;
			}
			set
			{
				if ((this._fecha_se != value))
				{
					this.Onfecha_seChanging(value);
					this.SendPropertyChanging();
					this._fecha_se = value;
					this.SendPropertyChanged("fecha_se");
					this.Onfecha_seChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_se", DbType="VarChar(20)")]
		public string estado_se
		{
			get
			{
				return this._estado_se;
			}
			set
			{
				if ((this._estado_se != value))
				{
					this.Onestado_seChanging(value);
					this.SendPropertyChanging();
					this._estado_se = value;
					this.SendPropertyChanged("estado_se");
					this.Onestado_seChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_detalles_se", DbType="VarChar(50)")]
		public string detalles_se
		{
			get
			{
				return this._detalles_se;
			}
			set
			{
				if ((this._detalles_se != value))
				{
					this.Ondetalles_seChanging(value);
					this.SendPropertyChanging();
					this._detalles_se = value;
					this.SendPropertyChanged("detalles_se");
					this.Ondetalles_seChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_se_idusuario", DbType="Int")]
		public System.Nullable<int> se_idusuario
		{
			get
			{
				return this._se_idusuario;
			}
			set
			{
				if ((this._se_idusuario != value))
				{
					if (this._Usuarios.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onse_idusuarioChanging(value);
					this.SendPropertyChanging();
					this._se_idusuario = value;
					this.SendPropertyChanged("se_idusuario");
					this.Onse_idusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="servicio_calificaciones", Storage="_calificaciones", ThisKey="Idservicio", OtherKey="servicioId")]
		public EntitySet<calificaciones> calificaciones
		{
			get
			{
				return this._calificaciones;
			}
			set
			{
				this._calificaciones.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuarios_servicio", Storage="_Usuarios", ThisKey="se_idusuario", OtherKey="Idusuario", IsForeignKey=true)]
		public Usuarios Usuarios
		{
			get
			{
				return this._Usuarios.Entity;
			}
			set
			{
				Usuarios previousValue = this._Usuarios.Entity;
				if (((previousValue != value) 
							|| (this._Usuarios.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuarios.Entity = null;
						previousValue.servicio.Remove(this);
					}
					this._Usuarios.Entity = value;
					if ((value != null))
					{
						value.servicio.Add(this);
						this._se_idusuario = value.Idusuario;
					}
					else
					{
						this._se_idusuario = default(Nullable<int>);
					}
					this.SendPropertyChanged("Usuarios");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_calificaciones(calificaciones entity)
		{
			this.SendPropertyChanging();
			entity.servicio = this;
		}
		
		private void detach_calificaciones(calificaciones entity)
		{
			this.SendPropertyChanging();
			entity.servicio = null;
		}
	}
	
	public partial class OrganizarPaseadorResult
	{
		
		private int _Idpaseador;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private System.Nullable<long> _telefono;
		
		private string _correo;
		
		private string _barrio;
		
		private System.Nullable<double> _precio;
		
		public OrganizarPaseadorResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idpaseador", DbType="Int NOT NULL")]
		public int Idpaseador
		{
			get
			{
				return this._Idpaseador;
			}
			set
			{
				if ((this._Idpaseador != value))
				{
					this._Idpaseador = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="BigInt")]
		public System.Nullable<long> telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this._telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this._correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_barrio", DbType="VarChar(50)")]
		public string barrio
		{
			get
			{
				return this._barrio;
			}
			set
			{
				if ((this._barrio != value))
				{
					this._barrio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Float")]
		public System.Nullable<double> precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this._precio = value;
				}
			}
		}
	}
	
	public partial class ConsultarpaseadorResult
	{
		
		private int _Idpaseador;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private System.Nullable<long> _telefono;
		
		private string _correo;
		
		private string _barrio;
		
		private string _tipo_doc;
		
		private int _documento;
		
		public ConsultarpaseadorResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idpaseador", DbType="Int NOT NULL")]
		public int Idpaseador
		{
			get
			{
				return this._Idpaseador;
			}
			set
			{
				if ((this._Idpaseador != value))
				{
					this._Idpaseador = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="BigInt")]
		public System.Nullable<long> telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this._telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this._correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_barrio", DbType="VarChar(50)")]
		public string barrio
		{
			get
			{
				return this._barrio;
			}
			set
			{
				if ((this._barrio != value))
				{
					this._barrio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_doc", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string tipo_doc
		{
			get
			{
				return this._tipo_doc;
			}
			set
			{
				if ((this._tipo_doc != value))
				{
					this._tipo_doc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_documento", DbType="Int NOT NULL")]
		public int documento
		{
			get
			{
				return this._documento;
			}
			set
			{
				if ((this._documento != value))
				{
					this._documento = value;
				}
			}
		}
	}
	
	public partial class buscarpaseadorNResult
	{
		
		private int _Idpaseador;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private System.Nullable<long> _telefono;
		
		private string _correo;
		
		private string _barrio;
		
		private System.Nullable<double> _precio;
		
		public buscarpaseadorNResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idpaseador", DbType="Int NOT NULL")]
		public int Idpaseador
		{
			get
			{
				return this._Idpaseador;
			}
			set
			{
				if ((this._Idpaseador != value))
				{
					this._Idpaseador = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="BigInt")]
		public System.Nullable<long> telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this._telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this._correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_barrio", DbType="VarChar(50)")]
		public string barrio
		{
			get
			{
				return this._barrio;
			}
			set
			{
				if ((this._barrio != value))
				{
					this._barrio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Float")]
		public System.Nullable<double> precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this._precio = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
